files_in = '{files_in}'
file_out = '{file_out}'

detector_db = 'next100'
binning = 'regular' #'sipm'
# If 'sipm', (x, y) is taken from SiPM DB, z from the values below
# If 'regular', voxelization is given by the values below
min_pos   = (-500, -500, 0)
max_pos  = (500, 500, 1300)
voxel_size  = (5, 5, 4)


data_type = '0nubb'
city = 'sophronia' # 'beersheba'

blob_ener_loss_th = 0.25
blob_ener_th = None

mc_label = True
reco_label = True

interpol_params = dict(interpolate = False, sample_width = [15.55, 15.55], interp_thr = 0.2)

Rmax = 500
ghost_label = 0
max_distance = np.sqrt(3)

add_isaura_info = False

#parameters if I want to add isaura tracks for nexus
ethr     = 10.0
min_vox  = 3
blob_rad = 20
#voxel_size is the same as for the labelling

#parameters if I want to create graphs for nexus
voxel_tablename = 'MCVoxels'
coords = ['x', 'y', 'z']
ener_label = 'ener'
add_distant_edges = False
#max_distance is the same as for the labelling